version: "3"

services:
  app:
    image: node:latest
    command: npm start
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_ENV=docker
    volumes:
      - .:/app:Z
    ports:
      - "80:80"

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./db:/data/db:Z
    expose:
      - 27017
    ports:
      - "27017:27017"
