node:
  image: node:latest
  command: "npm start"
  working_dir: /app
  links:
   - db
  environment:
   - NODE_ENV=docker
  volumes:
   - .:/app
  ports:
   - 3000:80

db:
  image: mongo:latest
  command: "--smallfiles"
  volumes:
   - ./db:/data/db
  expose:
   - 27017
